### ISSUE TITLE
Alternative for scopelint - detect variable capture in closures

### ISSUE THREAD

**Issue by omertuc** [kyoh86/scopelint#16]
scopelint does a great job of finding this apparently very common bug when writing Ginkgo tests:
https://github.com/kubernetes/kubernetes/issues/98213

looppointer or exportloopref don't flag it.

Do you know of any non-obsolete alternative that can do this job instead of scopelint?

Also, out of curiosity, why have you made scopelint obsolete?

**Comment by kyoh86** [comment]
> Do you know of any non-obsolete alternative that can do this job instead of scopelint?

Sorry, I don't know any alternative.
Maybe it is in [them](https://golangci-lint.run/usage/linters/).

> Also, out of curiosity, why have you made scopelint obsolete?

- Because that interface is obsolete.
  - Now, providing an analyzer to find diagnostics like those, we should use `x/tools/go/analysis`.
  - scopelint is forked from 'golint' in 2017. And it has not been refactored.
- And I found that diagnostics are just noise while a lot of false-positives are included.
  - Any analyzer CANNOT know if a closure is called soon.
  - So any variables in closures in the loop will be reported.

BTW:

If I should provide an alternative, I make it from scratch -- like [loopclosure](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/loopclosure)
(Note that the loopclosure is not alternative, it just find loop-variables in `go f()`.)

**Comment by omertuc** [comment]
> > Do you know of any non-obsolete alternative that can do this job instead of scopelint?
> 
> Sorry, I don't know any alternative.
> Maybe it is in [them](https://golangci-lint.run/usage/linters/).
> 
> > Also, out of curiosity, why have you made scopelint obsolete?
> 
> * Because that interface is obsolete.
>   
>   * Now, providing an analyzer to find diagnostics like those, we should use `x/tools/go/analysis`.
>   * scopelint is forked from 'golint' in 2017. And it has not been refactored.
> * And I found that diagnostics are just noise while a lot of false-positives are included.
>   
>   * Any analyzer CANNOT know if a closure is called soon.
>   * So any variables in closures in the loop will be reported.
> 
> BTW:
> 
> If I should provide an alternative, I make it from scratch -- like [loopclosure](https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/loopclosure)
> (Note that the loopclosure is not alternative, it just find loop-variables in `go f()`.)

I see. Thank you for the explanation. I might try and build something out of that `loopclosure` thing for detecting this specific common pitfall with Ginkgo
